### PR TITLE
Dev

### LINKED ISSUE #179: Add Unsupported Browser Warnings (IE 10 or below, possibly others)
For IE 9 and below, the site doesn't work at all. We may come across other old browsers with similar issues (basically, anything that doesn't support HTML5).

We should detect whether the user has an unsupported browser, and if so, redirect them to a page that tells them to join us in 2016*.

*Possibly not those exact words.

### LINKED ISSUE #180: Buttons are different sizes
image

### LINKED ISSUE #187: UX: Make filter buttons easier to use
image

### LINKED ISSUE #189: Report detail page description format issues?
image

I thought we fixed this?

### LINKED ISSUE #193: guest user in quotes
Nonexistent user in the hamburger menu
datand_and_1__deploy_bi-portal-test__apps_fenrir__ssh_

Should be reworded
> Why am I "Guest User"?

so that it's more consistent across the site

make it open a new tab in hamburger and top menu

### PR DESCRIPTION
**Pull request by RyanSnodgrass**
New Features
===
### True Tableau Pass Through Authentication
Removing the need for the hideous Tableau login modal.

@JacobSonner discovered the URL for Tableau's SAML authentication; if we pop open an iframe and set the source to that URL, Tableau will pick up our CAS auth automatically, without requiring the user to click. So we're going back to putting a hidden iframe on the report page.

### Tableau Auto-Authentication on Datasets
The datasets page also requires Tableau authentication in order to download the blank workbook. We now use the same workarounds as on the report page to seamlessly authenticate.

### Partial Search
Users will type 3 or 4 letters in the typeahead, see the suggestions pop up, then hit enter, expecting to see search results matching the typeahead suggestions. While we can't get the search results to exactly match typeahead suggestions, we can get partial search.

### Description hide feature

User feedback has told us that on the report detail page, no one reads the description, instead they blow right over it and start at the pretty pictures. 

Since all of the report descriptions are atleast a paragraph long, we thought that we ought to hide the description with a 'read more' button. check below. 

We've grayed out the description field and added a border that cuts off the second line, looking like the page slips under the border

Closed
readmore-closed

Open
readmore-open

### Report Button
Added css properties to change report tableau filter buttons on hover.

### Hound CI for Ruby
Added the ruby defaults from hound into rubocop.yml. Linted several files.

fixes #187 
Bug Fixes
===
- Added foundation media query breakpoints for tableau buttons.
- Added another button size that increases on smaller screens to fit all the text. - fixes #180 
- Removed hardcoded references to egrantha in jobs.
- Guest user reworded. fixes #193 

### Extrapolated reports helper to 2 files
The code relating to checking and creating the buttons was extrapolated into it's own helper

### Office and Terms Listing Switched From 2 Wide to 3
On PermissionGroup page it lists all terms associated. On office page, it lists all terms it's associated with. Changed this from 2 wide to 3 wide so the page is shorter and easier to scroll. Changed the alignment from centered to left align on all screens, but small will be centered

### Unsupported Browser Warning
IE support for this application is only for versions 11 and above. Any other version will display a warning error and users are restricted from using the app. fixes #179

### Left Align Dataset Description
Description layout is changed from center to left align. fixes #189

### CODE REVIEW

File: app/assets/javascripts/read_more.js [hunk 1]
```diff
@@ -0,0 +1,16 @@
+// this code changes the read more button to drop down and go back up-
+// displaying more or displaying less description
+$(document).ready(function () {
+  $('#read-button').click(function () {
+    $('#read-button').toggleClass('read-more-button read-less-button');
+
+    if ($('#read-button').text() == 'Read Less') {
+      $('#description').addClass('hide-description-length');
```
Comment (RyanSnodgrass) [inline app/assets/javascripts/read_more.js]: Codacy Issue found: ["$" is not defined.](https://www.codacy.com/app/ryansnodgrass-dev/fenrir/file/2626511313/issues/source?bid=3285068&fileBranchId=3316712#l8)

File: app/assets/javascripts/read_more.js [hunk 2]
```diff
@@ -0,0 +1,16 @@
...
+    } else {
+      $('#description').removeClass('hide-description-length');
+    }
+
+    $('.read-less-button').text('Read Less');
+    $('.read-more-button').text('Read More');
```
Comment (RyanSnodgrass) [inline app/assets/javascripts/read_more.js]: Codacy Issue found: ["$" is not defined.](https://www.codacy.com/app/ryansnodgrass-dev/fenrir/file/2626511313/issues/source?bid=3285068&fileBranchId=3316712#l14)

File: app/assets/javascripts/read_more.js [hunk 3]
```diff
@@ -0,0 +1,16 @@
+// this code changes the read more button to drop down and go back up-
+// displaying more or displaying less description
+$(document).ready(function () {
+  $('#read-button').click(function () {
+    $('#read-button').toggleClass('read-more-button read-less-button');
+
+    if ($('#read-button').text() == 'Read Less') {
+      $('#description').addClass('hide-description-length');
+    } else {
+      $('#description').removeClass('hide-description-length');
```
Comment (RyanSnodgrass) [inline app/assets/javascripts/read_more.js]: Codacy Issue found: ["$" is not defined.](https://www.codacy.com/app/ryansnodgrass-dev/fenrir/file/2626511313/issues/source?bid=3285068&fileBranchId=3316712#l10)

Comment (RyanSnodgrass) [inline app/assets/javascripts/read_more.js]: Codacy Issue found: [Strings must use doublequote.](https://www.codacy.com/app/ryansnodgrass-dev/fenrir/file/2626511313/issues/source?bid=3285068&fileBranchId=3316712#l10)

File: app/assets/javascripts/read_more.js [hunk 4]
```diff
@@ -0,0 +1,16 @@
+// this code changes the read more button to drop down and go back up-
+// displaying more or displaying less description
+$(document).ready(function () {
+  $('#read-button').click(function () {
```
Comment (RyanSnodgrass) [inline app/assets/javascripts/read_more.js]: Codacy Issue found: [Strings must use doublequote.](https://www.codacy.com/app/ryansnodgrass-dev/fenrir/file/2626511313/issues/source?bid=3285068&fileBranchId=3316712#l4)

File: app/assets/javascripts/read_more.js [hunk 5]
```diff
@@ -0,0 +1,16 @@
...
+    $('#read-button').toggleClass('read-more-button read-less-button');
+
+    if ($('#read-button').text() == 'Read Less') {
```
Comment (RyanSnodgrass) [inline app/assets/javascripts/read_more.js]: Codacy Issue found: ["$" is not defined.](https://www.codacy.com/app/ryansnodgrass-dev/fenrir/file/2626511313/issues/source?bid=3285068&fileBranchId=3316712#l7)

File: app/assets/javascripts/read_more.js [hunk 6]
```diff
@@ -0,0 +1,16 @@
+// this code changes the read more button to drop down and go back up-
+// displaying more or displaying less description
+$(document).ready(function () {
+  $('#read-button').click(function () {
+    $('#read-button').toggleClass('read-more-button read-less-button');
```
Comment (RyanSnodgrass) [inline app/assets/javascripts/read_more.js]: Codacy Issue found: ["$" is not defined.](https://www.codacy.com/app/ryansnodgrass-dev/fenrir/file/2626511313/issues/source?bid=3285068&fileBranchId=3316712#l5)

File: app/assets/javascripts/read_more.js (hunk 4 above)
Comment (RyanSnodgrass) [inline app/assets/javascripts/read_more.js]: Codacy Issue found: ["$" is not defined.](https://www.codacy.com/app/ryansnodgrass-dev/fenrir/file/2626511313/issues/source?bid=3285068&fileBranchId=3316712#l4)

File: app/assets/javascripts/read_more.js [hunk 7]
```diff
@@ -0,0 +1,16 @@
...
+
+    if ($('#read-button').text() == 'Read Less') {
+      $('#description').addClass('hide-description-length');
+    } else {
+      $('#description').removeClass('hide-description-length');
+    }
+
+    $('.read-less-button').text('Read Less');
```
Comment (RyanSnodgrass) [inline app/assets/javascripts/read_more.js]: Codacy Issue found: ["$" is not defined.](https://www.codacy.com/app/ryansnodgrass-dev/fenrir/file/2626511313/issues/source?bid=3285068&fileBranchId=3316712#l13)

File: app/assets/javascripts/read_more.js [hunk 8]
```diff
@@ -0,0 +1,16 @@
+// this code changes the read more button to drop down and go back up-
+// displaying more or displaying less description
+$(document).ready(function () {
```
Comment (RyanSnodgrass) [inline app/assets/javascripts/read_more.js]: Codacy Issue found: ["$" is not defined.](https://www.codacy.com/app/ryansnodgrass-dev/fenrir/file/2626511313/issues/source?bid=3285068&fileBranchId=3316712#l3)

File: app/assets/javascripts/read_more.js (hunk 2 above)
Comment (RyanSnodgrass) [inline app/assets/javascripts/read_more.js]: Codacy Issue found: ["$" is not defined.](https://www.codacy.com/app/ryansnodgrass-dev/fenrir/file/2626709340/issues/source?bid=3285068&fileBranchId=3316712#l14)

File: app/assets/javascripts/read_more.js (hunk 1 above)
Comment (RyanSnodgrass) [inline app/assets/javascripts/read_more.js]: Codacy Issue found: ["$" is not defined.](https://www.codacy.com/app/ryansnodgrass-dev/fenrir/file/2626709340/issues/source?bid=3285068&fileBranchId=3316712#l8)

File: app/assets/javascripts/read_more.js (hunk 3 above)
Comment (RyanSnodgrass) [inline app/assets/javascripts/read_more.js]: Codacy Issue found: ["$" is not defined.](https://www.codacy.com/app/ryansnodgrass-dev/fenrir/file/2626709340/issues/source?bid=3285068&fileBranchId=3316712#l10)

Comment (RyanSnodgrass) [inline app/assets/javascripts/read_more.js]: Codacy Issue found: [Strings must use doublequote.](https://www.codacy.com/app/ryansnodgrass-dev/fenrir/file/2626709340/issues/source?bid=3285068&fileBranchId=3316712#l10)

File: app/assets/javascripts/read_more.js (hunk 5 above)
Comment (RyanSnodgrass) [inline app/assets/javascripts/read_more.js]: Codacy Issue found: ["$" is not defined.](https://www.codacy.com/app/ryansnodgrass-dev/fenrir/file/2626709340/issues/source?bid=3285068&fileBranchId=3316712#l7)

File: app/assets/javascripts/read_more.js (hunk 4 above)
Comment (RyanSnodgrass) [inline app/assets/javascripts/read_more.js]: Codacy Issue found: [Strings must use doublequote.](https://www.codacy.com/app/ryansnodgrass-dev/fenrir/file/2626709340/issues/source?bid=3285068&fileBranchId=3316712#l4)

File: app/assets/javascripts/read_more.js (hunk 6 above)
Comment (RyanSnodgrass) [inline app/assets/javascripts/read_more.js]: Codacy Issue found: ["$" is not defined.](https://www.codacy.com/app/ryansnodgrass-dev/fenrir/file/2626709340/issues/source?bid=3285068&fileBranchId=3316712#l5)

File: app/assets/javascripts/read_more.js (hunk 4 above)
Comment (RyanSnodgrass) [inline app/assets/javascripts/read_more.js]: Codacy Issue found: ["$" is not defined.](https://www.codacy.com/app/ryansnodgrass-dev/fenrir/file/2626709340/issues/source?bid=3285068&fileBranchId=3316712#l4)

File: app/assets/javascripts/read_more.js (hunk 7 above)
Comment (RyanSnodgrass) [inline app/assets/javascripts/read_more.js]: Codacy Issue found: ["$" is not defined.](https://www.codacy.com/app/ryansnodgrass-dev/fenrir/file/2626709340/issues/source?bid=3285068&fileBranchId=3316712#l13)

File: app/assets/javascripts/read_more.js (hunk 8 above)
Comment (RyanSnodgrass) [inline app/assets/javascripts/read_more.js]: Codacy Issue found: ["$" is not defined.](https://www.codacy.com/app/ryansnodgrass-dev/fenrir/file/2626709340/issues/source?bid=3285068&fileBranchId=3316712#l3)
